version: 2.0
jobs:
  build:
    working_directory: /go/src/github.com/GetTerminus/convox-off-cluster-builder
    docker:
      - image: getterminus/cci-build-golang:20180319a
    steps:
      - checkout
      - run:
          name: Ginkgo Tests
          command: ginkgo -r --randomizeAllSpecs --randomizeSuites --failOnPending --cover --trace --race --progress
      - run: pwd
      - run: ls
      - run: touch coverage.txt; find . -name *.coverprofile | xargs -l cat >> coverage.txt
      - run: cat coverage.txt
      - run: bash <(curl -s https://codecov.io/bash)
