version: 2.0
jobs:
  build:
    working_directory: /go/src/github.com/GetTerminus/convox-off-cluster-builder
    docker:
      - image: getterminus/cci-build-golang:20171218
    steps:
      - checkout
      - run:
          name: Ginkgo Tests
          command: ginkgo -r --randomizeAllSpecs --randomizeSuites --failOnPending --cover --trace --race --progress
